"""Generate test fixtures from captured queries."""

from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent, indent

from .capture import CaptureSession, CapturedQuery


def generate_sql_fixtures(session: CaptureSession, output_dir: str | Path) -> list[Path]:
    """Generate SQL fixture files from a capture session.

    Creates:
    - setup.sql: DDL + INSERT statements
    - queries.sql: SELECT statements
    - teardown.sql: Cleanup statements

    Returns:
        List of generated file paths.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    files = []

    setup_lines = ["-- Generated by query-lapse", "-- Setup: DDL and data insertion", ""]
    query_lines = ["-- Generated by query-lapse", "-- Queries for replay testing", ""]
    teardown_lines = ["-- Generated by query-lapse", "-- Teardown: cleanup", ""]

    tables_seen = set()

    for q in session.queries:
        sql_upper = q.sql.strip().upper()

        if sql_upper.startswith(("CREATE", "ALTER")):
            setup_lines.append(q.sql.rstrip(";") + ";")
            setup_lines.append("")
            # Track table names for teardown
            for word in q.sql.split():
                if word.upper() == "TABLE":
                    idx = q.sql.upper().split().index("TABLE")
                    parts = q.sql.split()
                    if idx + 1 < len(parts):
                        table = parts[idx + 1].strip("(").strip('"').strip("'")
                        if table.upper() not in ("IF", "EXISTS"):
                            tables_seen.add(table)
                    break

        elif sql_upper.startswith("INSERT"):
            if q.params:
                comment = f"-- Params: {json.dumps(q.params, default=str)}"
                setup_lines.append(comment)
            setup_lines.append(q.sql.rstrip(";") + ";")
            setup_lines.append("")

        elif sql_upper.startswith(("SELECT", "WITH")):
            if q.params:
                comment = f"-- Params: {json.dumps(q.params, default=str)}"
                query_lines.append(comment)
            if q.result_sample:
                query_lines.append(f"-- Expected {len(q.result_sample)} rows (sample)")
            query_lines.append(q.sql.rstrip(";") + ";")
            query_lines.append("")

    for table in sorted(tables_seen):
        teardown_lines.append(f"DROP TABLE IF EXISTS {table};")

    for name, lines in [("setup.sql", setup_lines), ("queries.sql", query_lines), ("teardown.sql", teardown_lines)]:
        path = output_dir / name
        path.write_text("\n".join(lines), encoding="utf-8")
        files.append(path)

    return files


def generate_json_snapshots(session: CaptureSession, output_dir: str | Path) -> list[Path]:
    """Generate JSON snapshot files for queries with result samples.

    Each SELECT query with results gets its own snapshot file.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    files = []

    select_idx = 0
    for q in session.queries:
        if q.result_sample and q.sql.strip().upper().startswith(("SELECT", "WITH")):
            snapshot = {
                "sql": q.sql,
                "params": q.params,
                "result": q.result_sample,
                "rows_affected": q.rows_affected,
            }
            path = output_dir / f"query_{select_idx:04d}.json"
            path.write_text(json.dumps(snapshot, indent=2, default=str), encoding="utf-8")
            files.append(path)
            select_idx += 1

    return files


def generate_pytest_fixtures(session: CaptureSession, output_path: str | Path) -> Path:
    """Generate a pytest fixture file with assertion templates.

    Creates a conftest.py with:
    - Database setup/teardown fixtures
    - Individual test functions for each captured SELECT query
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        '"""Auto-generated test fixtures by query-lapse."""',
        "",
        "import json",
        "import sqlite3",
        "from pathlib import Path",
        "",
        "import pytest",
        "",
        "",
        "@pytest.fixture",
        "def db_connection(tmp_path):",
        '    """Create a test database with captured schema and data."""',
        '    db_path = tmp_path / "test.db"',
        "    conn = sqlite3.connect(str(db_path))",
        "    conn.row_factory = sqlite3.Row",
        "",
    ]

    # Inline setup SQL
    for q in session.queries:
        sql_upper = q.sql.strip().upper()
        if sql_upper.startswith(("CREATE", "INSERT", "ALTER")):
            escaped = q.sql.replace("'", "\\'").replace("\n", " ")
            if q.params:
                lines.append(f"    conn.execute('{escaped}', {json.dumps(q.params, default=str)})")
            else:
                lines.append(f"    conn.execute('{escaped}')")

    lines.extend([
        "    conn.commit()",
        "    yield conn",
        "    conn.close()",
        "",
        "",
    ])

    # Generate test for each SELECT
    select_idx = 0
    for q in session.queries:
        if q.result_sample and q.sql.strip().upper().startswith(("SELECT", "WITH")):
            escaped_sql = q.sql.replace("'", "\\'").replace("\n", " ")
            lines.append(f"def test_query_{select_idx:04d}(db_connection):")
            lines.append(f'    """Test: {escaped_sql[:60]}..."""')

            if q.params:
                lines.append(f"    cursor = db_connection.execute('{escaped_sql}', {json.dumps(q.params, default=str)})")
            else:
                lines.append(f"    cursor = db_connection.execute('{escaped_sql}')")

            lines.append("    rows = cursor.fetchall()")
            lines.append("    columns = [d[0] for d in cursor.description]")
            lines.append("    results = [dict(zip(columns, row)) for row in rows]")
            lines.append("")
            lines.append(f"    assert len(results) >= {len(q.result_sample)}")

            if q.result_sample:
                first = q.result_sample[0]
                for key, value in first.items():
                    if isinstance(value, (int, float)):
                        lines.append(f"    assert results[0]['{key}'] == {value!r}")
                    elif isinstance(value, str):
                        lines.append(f"    assert isinstance(results[0]['{key}'], str)")

            lines.append("")
            lines.append("")
            select_idx += 1

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path
